/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.claudioaltamura.java.pdf;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;

public class JavaPdf {
    public static void main(String[] args) {
        var document = new Document();
        try {
            var tmpdir = System.getProperty("java.io.tmpdir");
            var writer = PdfWriter.getInstance(document, new FileOutputStream(tmpdir + "/PreparingFood.pdf"));
            document.open();
            var text = """
                    Preparing eggs
                    He was hungry. He walked to the kitchen. He got out some eggs. He took out some oil. He placed a skillet on the stove. Next, he turned on the heat. He poured the oil into the skillet. He cracked the eggs into a bowl. He stirred the eggs. Then, he poured them into the hot skillet. He waited while the eggs cooked. They cooked for two minutes. He heard them cooking. They popped in the oil.
                                        
                    Next, he put the eggs on a plate. He placed the plate on the dining room table. He loved looking at his eggs. They looked pretty on the white plate. He sat down in the large wooden chair. He thought about the day ahead. He ate the eggs with a spoon. They were good.
                    """;
            document.add(new Paragraph(text));
            document.close();
            writer.close();
        } catch (DocumentException | FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}