/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.claudioaltamura.java.pdf;

import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.parser.*;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.List;

import static de.claudioaltamura.java.pdf.RecipePdfAssert.assertThat;


class RecipePdfTest {

    @Test void scrambledEggs() throws IOException, DocumentException {
        var recipePdf = new RecipePdf();
        var recipe = RecipeFactory.getScrambledEggsRecipe();
        var pdf = recipePdf.printRecipe(recipe);

        var pdfReader = new PdfReader(pdf);
        PdfReaderContentParser parser = new
                PdfReaderContentParser(pdfReader);
        var recipeTextRenderListener = new RecipeTextRenderListener();
        parser.processContent(1, recipeTextRenderListener);
        pdfReader.close();

        assertThat(recipeTextRenderListener)
                .hasTitle("Scrambled eggs")
                .containsIngredients(List.of("butter", "salt"))
                .hasStepSize(6);
    }
}